# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Build

on:
  pull_request:
  workflow_dispatch: # Allow running manually from web UI

jobs:
  package:
    name: Maven Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        # --batch-mode: Disable interactive input, making logs cleaner for CI.
        # -show-version: Print Maven and JDK version info.
        # --update-snapshots: Force update of snapshot dependencies.
        # --errors: Show full error stack traces on failure.
        # -DskipTests: Skip running tests. They should be run locally with custom credentials, see CONTRIBUTING.md.
        run: ./mvnw --batch-mode -show-version --update-snapshots --errors package -DskipTests
